name: Build API Image

on:
  push:
    tags:
      - 'console-api/v*'

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    name: Build Docker image
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      tag: ${{ github.event.ref }}
