name: Release App

on:
  workflow_call:
    inputs:
      app:
        description: 'The app to release'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.app }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Diffs
        id: bumps
        run: |
          package_file="apps/${{ inputs.app }}/package.json"
          
          if [ ! -f "$package_file" ]; then
            echo "Error: Package file $package_file does not exist."
            exit 1
          fi
          
          current_version=$(jq -r '.version' "$package_file")
          current_version="console-${inputs.app}/v$current_version"
          
          if ! git rev-parse "$current_version" >/dev/null 2>&1; then
            echo "version=$current_version" >> $GITHUB_OUTPUT
          fi

      - name: Echo the version and changelog
        run: |
          echo "---- version start ----"
          echo "${{ steps.bumps.outputs.version }}"
          echo "---- version end ----"

      - name: Create Release
        if: ${{ steps.bumps.outputs.version != '' }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bumps.outputs.version }}
          release_name: ${{ steps.bumps.outputs.version }}
          prerelease: true