name: Draft Api Release

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/package.json'

permissions:
  contents: write

jobs:
  release:
    name: Create Release Draft
    uses: ./.github/workflows/release-app.yml
    secrets: inherit
    with:
      app: api