name: Release Deploy Web

on:
  push:
    branches:
      - main
    paths:
      - 'apps/deploy-web/package.json'

jobs:
  release:
    name: Create Release
    uses: ./.github/workflows/create-github-release.yml
    secrets: inherit
    with:
      app: deploy-web

  build:
    needs: release
    name: Build Docker image
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    permissions:
      contents: write
      packages: write
    with:
      tag: ${{ needs.release.outputs.version }}