name: Release API

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/package.json'

permissions:
  contents: write

jobs:
  release:
    name: Create Release Draft
    uses: ./.github/workflows/create-github-release.yml
    secrets: inherit
    with:
      app: api

    build:
      needs: release
      name: Build Docker image
      uses: ./.github/workflows/build-image.yml
      secrets: inherit
      with:
        tag: ${{ needs.release.outputs.version }}