name: Release App

on:
  workflow_call:
    inputs:
      app:
        description: 'The app to release'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.app }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Diffs
        id: bumps
        run: |
          package_file="apps/${{ inputs.app }}/package.json"
          
          if [ ! -f "$package_file" ]; then
            echo "Error: Package file $package_file does not exist."
            exit 1
          fi
          
          current_version=$(jq -r '.version' "$package_file")
          
          if [ "${{ inputs.app }}" = "deploy-web" ]; then
            current_version="console-web/v$current_version"
          elif [ "${{ inputs.app }}" = "api" ]; then
            current_version="console-api/v$current_version"
          else
            echo "Error: Unsupported app type '${{ inputs.app }}'."
            exit 1
          fi
          
          has_tag=$(git rev-parse "$current_version" >/dev/null 2>&1 && echo "true" || echo "false")
          
          if [ "$has_tag" = "false" ]; then
            echo "version=$current_version" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        if: ${{ steps.bumps.outputs.version != '' }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bumps.outputs.version }}
          release_name: ${{ steps.bumps.outputs.version }}
          prerelease: true